import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import HomepageFeatures from '@site/src/components/HomepageFeatures';

import Heading from '@theme/Heading';
import styles from './index.module.css';

// Generated by the blog plugin on every build, so this always tracks the newest post.
import blogList from '@site/.docusaurus/docusaurus-plugin-content-blog/default/blog-post-list-prop-default.json';

function LatestPostTicker() {
  const latest = blogList?.items?.find((post) => !post.unlisted);
  if (!latest) {
    return null;
  }

  const label = `📖  Latest Blog:  ${latest.title}`;
  // One label per group; two identical groups loop seamlessly at translateX(-50%),
  // so a single item appears to scroll round and round through the small window.
  const group = (
    <div className={styles.tickerGroup} aria-hidden="true">
      <span className={styles.tickerItem}>
        {label}
        <span className={styles.tickerSep}>•</span>
      </span>
    </div>
  );

  return (
    <Link
      to={latest.permalink}
      className={styles.ticker}
      aria-label={`Latest post: ${latest.title}`}>
      <div className={styles.tickerTrack}>
        {group}
        {group}
      </div>
    </Link>
  );
}

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className={clsx('hero hero--primary', styles.heroBanner)}>
      <div className="container">
        <Heading as="h1" className="hero__title">
          {siteConfig.title}
        </Heading>
        <p className="hero__subtitle">{siteConfig.tagline}</p>
        <LatestPostTicker />
      </div>
    </header>
  );
}

export default function Home() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title={`Hello from ${siteConfig.title}`}
      description="Description will go into a meta tag in <head />">
      <HomepageHeader />
      <main>
        <HomepageFeatures />
      </main>
    </Layout>
  );
}
